### ISSUE TITLE
gem5 dependency arrow

### ISSUE THREAD

**Issue by mshiryaev** [shioyadan/Konata#11]
Hello, 

I am using the latest gem5 release (v22.1) and the latest pre-built Konata (v0.38).
I see that "View->Dependency arrow" menu option is available but it doesn't change displaying in any way.
The trace was collected with "--debug-flags=O3PipeView,O3CPUAll".

Could you please clarify what is the proper way to enable dependency arrow for gem5 trace (maybe some additional options, patches should be applied)?

**Comment by shioyadan** [comment]
Hello,

There are no operations required other than to add O3PipeView and O3CPUAll.

The dependent arrow feature is implemented by parsing physical register numbers contained in the gem5 log, but it is vulnerable because it relies on unstructured debug messages. Perhaps the message format has changed in the latest gem5. I will check it, so please wait a while.

**Comment by shioyadan** [comment]
I found that the log format has changed slightly in the latest gem5, so I made it compatible with the latest format. I also found bugs related to the dependency arrow feature and fixed them.

If you can try the latest commits, please try it. If you cannot try it yourself, please try it after I release a pre-built binary with the fixes. I will release it soon.

**Comment by mshiryaev** [comment]
@shioyadan
I validated Konata from master branch, now dependency arrows are displayed with the latest gem5.
Thank you for the fix!
