### ISSUE TITLE
How to make pipeline stage like 1/2/3/4 invisible？

### ISSUE THREAD

**Issue by h3yb** [shioyadan/Konata#12]
![image](https://user-images.githubusercontent.com/125844520/219997805-b16e398a-3eed-4b4b-a61b-d14216a5858b.png)
HElP!
How to make pipeline stage in the red box invisible？ I mean all these 1234 stages.
I tried to add extra  RETIRE Instructions but was there any other way?'
thank you.

**Comment by shioyadan** [comment]
I am not sure how you want to display the pipeline. 

If you want to retire the instructions there, you can use the "R" command. 
If you want to end the stages there, you can use the "E" command.

https://github.com/shioyadan/Konata/blob/master/docs/kanata-log-format.md

If you can explain a little more, I might be able to help.

**Comment by h3yb** [comment]
Thank you for your reply.
I want to to analyze the debug log by Kanata, which is similar to gem5 pipeline log.

Now I have to add extra R commands after each Stage, I want to let each Stage immediately (=after a cycle) retire.
I mean is there a way to do it without extra R command.
つまり、いちいちリタイアせずにすべての1や２のようなセルが見えるようにしたいです。
難しければ何もしなくても構わないです。

**Comment by shioyadan** [comment]
Thank you for your explanation. I probably understood your request. At this moment, there is no other way than to explicitly output the R command to retire an instruction.

It is technically possible to automatically close an instruction that has not been retired, but it could greatly increase the load of parsing. This is because it is impossible to know whether it has not yet been retired or it should be closed automatically, without reaching the end of a log.

I suppose that the reason for your request is that you do not want to complicate the structure by outputting R after waiting for one cycle (I assume some sort of buffer is needed). Is this right? 

If this is right, I am considering adding a feature to output a command in the future after N cycles. With this feature, R can be output immediately just after the start of the last stage.

**Comment by h3yb** [comment]
Thank you for your reply.
I tried to change the algorithm to achieve this effect, so I don't need to bother you to modify the program~
thank you.

**Comment by shioyadan** [comment]
By the way, do you use Konata for your own hardware design or simulator development? 
If so, would you tell me about your design? 
I am interested in how you and other people are using it.

**Comment by h3yb** [comment]
My colleague use Konata to analyze Gem5 pipeline, and our project is to use Gem5 to simulate a chip (Kunpeng) that we developed ourselves. 
My part is unified-bus, I use Konata to analyze the request pipeline for debug.

**Comment by shioyadan** [comment]
Thanks for sharing information about your project!
I am very happy that Konata is being used in the development of real products. 
I hope Konata is useful in your development.

**Comment by h3yb** [comment]
Konata is certainly useful, one of my colleagues who used to work for AMD for over 10 years is also using Konata!

**Comment by shioyadan** [comment]
That's great!
Conversely, a researcher in my lab moved to AMD a while ago, and I believe he is also using Konata.

Anyway, If you have any feature requests or find any bugs, please feel free to post them here again.

(As mentioned in another issue, it would be nice to have some kind of note-taking feature in Konata, but it has not been implemented yet.
