### ISSUE TITLE
Running konata on MacOS Moajve

### ISSUE THREAD

**Issue by vcgalpin** [shioyadan/Konata#2]
I have downloaded the most recent binary (v0.34, konata-darwin-x64.tar.gz) under MacOS Mojave and copied konata.app into /Applications.

When I launch it, it takes a minute or so to crash, and the crash report is attached below. (I also had this issue with a previous version on MacOS High Sierra)
[konata_2020-07-23-120239_Admins-MacBook-Air.txt](https://github.com/shioyadan/Konata/files/4965528/konata_2020-07-23-120239_Admins-MacBook-Air.txt)

**Comment by shioyadan** [comment]
Thank you for sending your report.

This issue seems to be derived from the following issue in Electron, which is a framework used in Konata. (I found the following issue from debug messages such as EXC_BREAKPOINT included in your crash report.

https://github.com/electron/electron/issues/19626

There are descriptions about some workarounds in the above issue page. Can you try to add --no-sandbox argument to Konata when you launch it? It may fix the issue.

> I can reproduce this issue with Electron 5.0.11, 6.0.12 and v7.0.0-beta.6, but not with Electron 4.2.11.
> I also can't reproduce it if I start the app with --no-sandbox argument.--disable-gpu argument does not seem to have any effect. I'm using macOS 10.14.6 and electron-builder 21.2.0.

> I can no longer reproduce this bug after updating my system to macOS 10.15.1 (Catalina). Looks like it occurs only on macOS 10.14.x. running Electron >= 5.x app packaged for MAS.

**Comment by vcgalpin** [comment]
Thank you for your quick response. Using --no-sandbox does not immediately fix the problem, but I’ll look at the link you sent to see if I can develop a better understanding. I’ll let you know if I find a solution.

Unfortunately, I don’t plan to upgrade to macOS 10.15, but I will be upgrading to macOS 11 later in the year, so that may be a fix. I could also compile the software from source which may solve the problem.

Best wishes
Vashti

**Comment by shioyadan** [comment]
I performed further investigation and I understood that this issue is related to code signing required by Apple. Apple recently requires code signing to each binary and I think that my app cannot be launched without the code signing in any Mac OSs. Actually, my friend using the latest Mac OS couldn't launch this app.

The following issue page is related to this problem.
https://github.com/electron/electron/issues/22656

Sadly, code-signing licenses aren't free, but they seem to cost about $100 each year.

So, instead of using a pre-built binary, I recommend that you launch it manually. I modified some code and pushed it so that users can launch this app easily. Please try the following steps.

1. Install node.js from https://nodejs.org
2. Clone this repository
3. Move to the root directory of this repository
4. Type ```npm install``` (this step needs to be done once)
5. Type ```npx electron .``` (not "npm", but "npx")

**Comment by vcgalpin** [comment]
Thanks for the further information. I’ll look at your suggestion in the next few days.

Best wishes
Vashti

**Comment by vcgalpin** [comment]
And it works!

Thank you for your work. I am looking forward to using konata — so much better than an ascii view of the pipeline.

Best wishes
Vashti

**Comment by shioyadan** [comment]
I am very glad that Konata finally works on your machine!
I hope this tool will help you in your research/development.

For me, this issue is also an important opportunity to think about how to distribute this software to users. Maybe I will change how to distribute it from a pre-built binary...

Thank you.
