### ISSUE TITLE
Please provide guide to install konata

### ISSUE THREAD

**Issue by RaoShri** [shioyadan/Konata#4]
Hi,
I have downloaded the Linux zip file. Readme says run the file named Konata, but I dont have an application that can run it. Since I am a newbie,I do not know the command to execute it in terminal.
Please tell me what command to use to run the file and install konata
Regards,
Thanks

**Comment by shioyadan** [comment]
Hi RaoShri,

If you extract "konata-linux-x64.tar.gz", there should be a file "konata-linux-x64/konata", which is an executable and you can run it from your terminal. Note that, the size of the file is more than 100MB.

Another way (launch from the source) is as follows:
1. Install node.js from https://nodejs.org
2. Clone Konata repository.
3. Launch install.bat (Windows) or install.sh (Linux/MacOS).
4. Launch Konata from konata.vbs (Windows) or konata.sh (Linux/MacOS).

If Konata crashes due to lack of required libraries, please follow the instructions in README.md to install or contact us.

Regards,
